apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: imgproxy-release
data:
    values.yaml: ENC[AES256_GCM,data:ExSZSUa9bhNbGAY+n6yRCLeOSZUkr+qBalzMrDdCDCyLgmvfSx1y+SOGKq9Us+dimGKri+jzlDnnECZWpSk8yQr+iNsLFbjFyBJgj/fUzt6sOcKboxmR2/1BgJV2AlxBpg6O6lYsTaXNgoOP,iv:xCrhzT0pjO8T2riFLPV3A27ocBPHDoo8CAm6sLAP8Bk=,tag:7mcNm17M/4bEfvriciB2Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-21T15:05:11Z"
    mac: ENC[AES256_GCM,data:RrR+OIWQFVzVT/TALs6myQxw2nYyhtirUDtDVPznTnM5uRvuruweLVeBq41iOZVKa3DUXmn2ahuCPDooBf9aqtqpFqHuRYik6akTo234iVVWo/CFwTo+tQ3GQGbx7LlvvNm3yhafBPZIBRW/HpoJ/z03akszzzQyZuoMT7kZZjg=,iv:jFLyvykS5Uoh7d05BC3Zpb63lYIALNMKDYX5NtLWXVA=,tag:BEvaeLxGmWUeyh8k73z00w==,type:str]
    pgp:
        - created_at: "2022-01-21T15:05:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1T4MNvPMvS9ARAA0deJ5EettCA74e2fdcGngubR+ibiTCHuurr95xPoU6Kl
            ooDaDrwwOLM4y5SRknhKRS1KZrkkk2mxgPvQ8t96aIUyN2vK/EHTaAmIedyA2kJC
            iJsShnpQ64ayVpcay5/QC640owOhS1KN6tRasfrxsNImeKk34Xv2jDtAkIYW8Gjt
            CURj0pEkp2U682xVn3oQdpM/R8qCTGoRZOjH8CBvOKSya7lU48LhAzpzXeTFZ/6I
            APqeJdpAxYhscJ0gb+3BKjX9d/FKo9KF/IDa+sumX//tuvGwgRpj7Pcw1ti83F2U
            6rCBI92gfrjqJrOS4bhEwUEMkWTjkZQ3k1KpVOqRDkQ0yfksu0xggEYwuC05pLTX
            f9qu7ZV3M4hfejvBGP+sYQqlYFpl6c+TKhA+kuSimU7g6GqC2gswa5uf0ci0adS8
            7Bvwz+DStGNRSD2qB0OOmYvY988/4lyt5c+RzCyIMNpJ3QwmTLzrZ1nfUQHO+hHI
            zpJul8AIfq7QLdfpnNwmj5UruVAwgUCDPcwF5Br0NJ8oFmrvP1f4bPpH6U1y3W2d
            5csi1t957lBy9JIaoWQVRUK6Wrlt0KBfcHrN7axxWLcl0vjaO+pbEuYDDdGxcuo9
            l+eK8bKRKtgJfhko36b4FZzJSRyw4sx431/EkNNQmQlu5CAxqX8kKVbo0O+VxI3U
            aAEJAhAT7wVzugnkG3Ju1cFYzGnMRNuV8yjyjaBgqydGMjnCZGlPtmBRWAaUqIy2
            hhGpXHw1inUiJDXviiWPSblVS4Msc5ZbdFIMEzMCzYaxiTTvipKTS0IFm+tkw0fm
            eJIW/n5Pribi
            =CQL6
            -----END PGP MESSAGE-----
          fp: 1F1AC5BB8445063D29B6F87C48A8C59F65012CDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
