---

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: imgproxy-release

data:
  values.yaml: ZmVhdHVyZXM6CiAgYXdzOgogICAgc2VjcmV0QWNjZXNzS2V5OiBNdm1kWjRmNUxwRDFSdnc1L3JDcWtHemlYL0ZOVWg3STFtTXJEY0dFCg==
