apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: oyster
stringData:
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:nm7DusBxAyfvsScBrjNy+AiH5lSRQIgcj/7kIa2f84g=,iv:r3tm8ChZGh/mhsvevnUeSVXG5Mo9BXEO40BtTluYyMM=,tag:bv+QgYppJfzAHO6es4scPQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xhGSqNStf3a05DGjnqFaQ9Nc/7AyRFNuFqti4YjqiPVQosgG4inE3A==,iv:m98/9xZxY+eoPvuYE5SrqeMa4qmI/WrO8pbPrUU524Y=,tag:ffL+bjf6dC2gjdgUzdnreA==,type:str]
    CHATENGINE_PRIVATE_KEY: ENC[AES256_GCM,data:lRil+gnyvEHZ79MhVAQ6SAEyeL8Q46MItVHWxqT6bTHznhMS,iv:coc1nj4Dh59WM0CPYIsln2yGZHDTd4TD3yW20iNUetI=,tag:NhKnVUlBzMcMqGbqEhtm/g==,type:str]
    CHATENGINE_SECRET: ENC[AES256_GCM,data:PoefrEVPYnzGymMgyBE9aa9LnWIlO/qQJWa/FIB+BRc=,iv:e6SaYdXet1/r/hpIlsbBj2KbO3TA+ampNgH2Shymg7E=,tag:m1Y5tamRd9Qm2opfKs+PHw==,type:str]
    COURIER_API_KEY: ENC[AES256_GCM,data:hepZ+Qbd15ztBbhGg9t1fQILCwZgUTg7KE7X/rY3ZQCi+2wf,iv:KsBIGEx7YKhtvhAsTDuPi+tvYzQ5e2XKOsX51ebfw68=,tag:JzMk28rsVzNDt4UuCmiWYA==,type:str]
    GCP_API_KEY: ENC[AES256_GCM,data:VkRpznIq0JcKzdZoLwEW3kjI/LX97qc6VWJ+4vFyddhqnnYltqw3,iv:ajHC/Ixb7DHib069Tlmh8pWoicNQFNmosUoVhXbzfZI=,tag:WTBuWDd7L6CzzmXzKsvuHQ==,type:str]
    HUBSPOT_API_KEY: ENC[AES256_GCM,data:K0IcRBExS1KVp+VgQKdpvwIzENfTyoPsAvELix3jTsvmaUaY,iv:2oxaVmNEEjokRtr+WlJPRV6Jqg7BrZ/P0fZcs/L9anI=,tag:9xaQ3EUm6LM7TsEZmYhU7g==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:FAG6T+aRTDYE8+NwonQZNHeYeo4bEBfupuCogrmclKP2f5jqWN7fUgyTBvrBzxqRFV4sRJkZSIVWofLRQfpEkZxTBU2MDCzp1NmenuGQfh/8LBYPzqlYXxIK08YyTVLtQHByyw==,iv:GBhlVPzv2MlaOlvdwrheMqITRH9jDPbehM8/wt+yVyE=,tag:WZf0TL5BRRwvZmhQhUaUxg==,type:str]
    OYSTER_ADMIN_SECRET: ENC[AES256_GCM,data:Iw/qkTDE1kQ=,iv:oQnV38M2xguyfq2WDl1GYaV5XEeUbsUXW6/6wn24wvg=,tag:4CLW+g+8EeJVsE0YqkDC8Q==,type:str]
    OYSTER_WEB_SEGMENT_WRITE_KEY: ENC[AES256_GCM,data:I5/yPX9etx93TOq6GnJ/yek1MGZbuqoKWq5LPjNzLpE=,iv:sCzzEa3Vb5ETtH6Y3BzP+PGgnEU9y9ZVitns5H/Z8f4=,tag:k4hIPCfK9Kqt5sW45l3X/Q==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:xREfAW8MC5QDidELDzXgY7aGlJkPrsezsE08vF9yBEduuRt4BgWcNfbVZWMh58vFR+o=,iv:3ug7f6D37tT+CNTYxD65IGauZ/NyT65C/maVjssJWP0=,tag:S72HECXpPj972VSQ8dRy9Q==,type:str]
    URLMETA_API_EMAIL: ENC[AES256_GCM,data:sfmh16rVENUyPITTh8il9NihJdFG2Q==,iv:11P4tv3ibtdlEBBBBKkXJprEsy1OOwp/EtbRrDtP6u4=,tag:IvqYPBKHfK1ekWe78RvBVA==,type:str]
    URLMETA_API_KEY: ENC[AES256_GCM,data:jtrs7A2viF0g0FPeUEgx7hwxcN4=,iv:6SC8JelUZWBBFdfLAmMBamcB9Kquzxr3z3pAXV8/Xhc=,tag:skkBMhYNwFyG9DucpNeyFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-10T18:13:35Z"
    mac: ENC[AES256_GCM,data:iC8ByzgclATVGO8/Ow42JDnRyBfPdwz2z4HklA225W51rUrXMh/adlXNZwYhvj2YXhAHlg3qq1MjFxjuj9cvalmGyOfdY2oQ54bejjFFg3YaphDe846e6/SCADv0o5eC6jG9phoVggeGrbbuk4ZFyD9GQP3e2sOgkjbhbHE9c9E=,iv:DhFOKFY2bqPkZGx43yFNAoJRswZ2GaJOfJnkwa6GcF8=,tag:Rv3Mr4goPZUcY0J61SinkA==,type:str]
    pgp:
        - created_at: "2021-12-10T18:13:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1T4MNvPMvS9ARAAhPh+wCm4rhz5Hbn/mbfydwy/EmNoLySFZiJ5SqlRfSt4
            ISWgDMMoFTtBZ3nObipBAI2FlizMVQT3Z6pdNoP8tvh41MhAxKB3fQpum1ZfHFrW
            JzKbbGmq9WVGz4DM8ThOffadEAVeoCcr1W9Dso0hCLpqlUf68S5ycs068K1gKI0h
            iJo+xu+1v7qxpjZlKR2KNdHYWtHSE1OkdrUtLrPLf7Mk8gZgfCza+5UZZ/gX/m2P
            jAasfTvjPuXmd1lMJmCcUG8l/+lpZK1BPOhSzgWfzgovaNwa+WLPSkn1CzLReiD7
            nmBcwQSv2qmSEO+gst8Qubseon46ptNKECtX/fs61TVA55qgEzghbtdmQBNR8Iw8
            NvaNHhKxwp0CaALfA6prWmkPLZ5EJeWEAk1RHfORjRAIUQaGWri5GyKYAzVGT5e3
            veR17Lp7Ks8fD6vD9+LSo/nwVCSra7rVJNKa4yc53qo+3+cZohoV6VBtmpD/rlTL
            qHB8UmUcYaDy9/fleLFXW3eTQL2K6Yy7LP3ef5OkYjIOsKU9RwT94i9R1EhvA0e9
            Oi9NJz07e8WbzO377hbwIeIY8YZ6hm5Ifl2Hd7OhkVtq8Sc6S5zshxMBlQ7UBC0l
            ggEsKRcUOsyU11lmhOPNVC0KVyVYGYW84l5xIu6PsICNeVpCSf5PtTs5osxOYf7U
            aAEJAhDuD1WLXN53rLe5x+0GPBXrZJob8B3q9/T/ah3VEoq2bq4YPv7FkBzNttiy
            pt6CwvG1sY3GEFiM9amXQNIVF+sJNHeCHk6xlRpCmctrpcByToX4RFcq4yJ6Qqje
            gwETLYfPuYdV
            =pQOi
            -----END PGP MESSAGE-----
          fp: 1F1AC5BB8445063D29B6F87C48A8C59F65012CDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
