apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: pilot
    labels:
        app: pilot
stringData:
    PILOT_DATABASE_URL: ENC[AES256_GCM,data:L3uy3aPmeketQdIpbKBEfBdEIFav2+hLpZkAvE1dDTfLC2wHp4a566THVTMGvJvLacI2FrAoVOyHIy+LAvO6e14AE0aRGonSgW/1HHvU/BxI+1YbmsrEmYNV+ZqZFqySYlMaFle5T+JPDbOE+EIyV4eek3xD6xmMZL7d,iv:Sf/KMp0llHbNScscn4OPC6sFQI79wj+lk0c+X7Rgido=,tag:TUbNIUy2978ZX2rMX+srrQ==,type:str]
    PILOT_FIREBASE_PROJECT_ID: ENC[AES256_GCM,data:BFmoX2MqnLhnuLs=,iv:qpmfYwQBhWMtcEqJU6kIqU0esj/hWCJqnWkdoCaTNgk=,tag:DvpBo+OqYMASxg12Pvl89w==,type:str]
    PILOT_HUBSPOT_KEY: ENC[AES256_GCM,data:9wDZ4/y1y64w84tRwPGwds0i02cR/imeVpwisQ/KGSxKonu/,iv:8cx02E9fZPxuiHijHcFOY1iMFPWQDL08TiTqc8u10F4=,tag:YrsSFOT7RB0H0SgjaQUMvA==,type:str]
    PILOT_IMAGEKIT_KEY: ENC[AES256_GCM,data:0tL+2PymjV25kurvgfe6RnaWPGBjki4iQT2gkSD/4dmlxWIG,iv:S/CRXAUgovmNVNCggzzT2EoDbbKPlLphwh9GANXsV0g=,tag:ezd7CvXG9Kwpfi74NZu+PA==,type:str]
    PILOT_MAILGUN_DOMAIN: ENC[AES256_GCM,data:QxdFoxKGUGMn91WfODp2Oy+gQ5AX,iv:Y+WzfnTwsC1SuRUHMEOk/ZbnFkFy/HOZeKtjD/gPFxk=,tag:NbNnVCElgfwESEflGbNY1w==,type:str]
    PILOT_MAILGUN_KEY: ENC[AES256_GCM,data:vPudLA3Djz8EBfQyPEcXOsT+1vWAkb9yOIHjbPkPiXMpc9nW,iv:BFoF38+Fgc+leow9qbnSdkgRXlXtA+n5hnfpTTohXX0=,tag:PB2wkON8zt5B5Sf+lFimuw==,type:str]
    PILOT_SECRET_BASE: ENC[AES256_GCM,data:RzWYN7xxU08M+tgya2aqmfrmDirk7VqfThmgO+IKlvewCvWTNMtCEuaWZ3VjHDHId17ciTwoujzoCA+cnxvwC2KjSUeRiuGJXH8VSqtH+wA9KEymSOoOeZv8RTjeRKqHmNmebfFxNqfTAG+K6s7qe69amN03hrMBnr2Q27ku6Uk=,iv:1Ep4LoQpNhCnJb8NKdUueb3NnWGHXOvgwyoPcj35vVc=,tag:OEmc9/2HATNr7NpMJvImsA==,type:str]
    PILOT_SENTRY_DSN: ENC[AES256_GCM,data:VzOsCvJQres0aU2v5wJoI0ezKqCtz/EuPeOWeiHO2cgNF4ZsWFci71VfrIrRM6ZWmXbE6B3b7tVbYhe5atn+hbNYgwAQsSozjg==,iv:zXRwj9iIqa1gD6AEhdNR190PGvThX5bpg/70RvVg4jE=,tag:WH9Y07J2EivUqPhPF8LUCQ==,type:str]
    PILOT_STRIPE_KEY: ENC[AES256_GCM,data:xn5sUfVkPy+qfnCuTiNghRPWwik9OVE+UlOHhNqlkRWSYuyMmVhjudF1SouP6BOC8R+xRZeZ7HDZStfucKFUcd3T4UbQTlapxBc9qqTmUQpj4RHggpNbYrc2SAkSsXW9raFJp12t/RiBi1g=,iv:R69hZqlTsCSmTNdsykskicepfD23aOg2EDJ8lo6ih8U=,tag:Nbm71PUgVwFApTKAqaz1Lg==,type:str]
    PILOT_STRIPE_SIGNING_SECRET: ENC[AES256_GCM,data:SJaTsXwZZtqbsYEqM1/KogLxNRESOwwSarUOnoPK3MALxTXbpw0=,iv:fGwjuf6m3cawOOB7nx51ztm2PF3he4zKf5mdM7lPjDM=,tag:SQPjOv2BQxjutLKN2VBYMg==,type:str]
    PILOT_URLMETA_ID: ENC[AES256_GCM,data:gUoPrfw6jpYaJKp+XgWrUtrSj99xUA==,iv:Q2jCtT2sCGILEPYfArSgfK2Q/CifhJ4BsWqN90ggegc=,tag:nx/GEY2NK/xA3inqfSIrWA==,type:str]
    PILOT_URLMETA_KEY: ENC[AES256_GCM,data:yigoo/81uRmElMZ7sMef5Llah9g=,iv:3nDetIzdjanf8TKyVWvBZMMnQ1S7OfilZaw6MySyRnM=,tag:iwyN7/aoHEbFbeHrIiK+rg==,type:str]
    OYSTER_ADMIN_KEY: ENC[AES256_GCM,data:AjYn/l1I8N4=,iv:1xoHE5A18SFue0kgfxyMkCakQ3cnJHy2RExVtVyuFXI=,tag:uDytkjfxkYnWRv9dfU1U7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-06T16:44:11Z"
    mac: ENC[AES256_GCM,data:h1M1VWv6A6aa3QJme/B82SLRCHfcNz+alJNvSWL51eTcsHiADp8FrxMcD3popzBPPvBYaqImAVbbSS4+o+v9fI/0c9THTBtMHaeaCwr6y8wZ6MJNtnmN3OnZxEGbntdwIOefzSjiblkKx3GBdvoBEmHPuVQeU5mKwsNbW7O2PVA=,iv:97brVzCb7iZZ25URsH6YywBtebVjE2BNcA1y8GItit8=,tag:gb7vv1HFaipylbhKjx1BWQ==,type:str]
    pgp:
        - created_at: "2021-12-06T16:44:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1T4MNvPMvS9ARAAqVcv2qYS2Ze13KJ/HkXsAJmy1xBxg6mnEPSfQJVusbI/
            rDC6MBYaMh26V3okiDMg4r3X9wSBKGlLHp6Elo5JpDrzonftQZOwg9hpICI1mYfw
            aqURM+Nkqz+/MWTZQK9n1XSHkNcmkq2erqNXdRerHhIx1rU101E0ic4STZg0b8mr
            upRhpkOQ3zRM2jmleyLIL93TFJ2Dy3f4Y0HXwyudQm7LFOv23A5B35ZHnM9jYVhK
            SV2PdnmA3ATzdXlQcab3iizRZ2oVQDakedH3LOgx3kB12Hl8GAyMo9EU5lF/uutM
            GEJ7+C/sLIKXYR8LGLWXgGlQe4mrd+EfEIRM1MBoGErd4ngI6PZTv/vyrwWEWDOO
            C9ER0AdkOndXpI5DDIIWqyK/csLaxHUmnE8InPvWNQ8kS0fKqvmwZU3qDieRceNT
            I0V6EFLBcEI5yAPVeQERULX/7F2HJ1NeMGHGtoyjlyakzFxDkG5zPSiDGvtsAfrY
            IQ5FkgKiBK/DWkvcaxORhrJuWJU1RMdf8708TEqwJs/f29RSt5meNWB3Sv3WhEjc
            hDhiaMAaG4wxjV/wjF3sply4wXgvNr6xq4FdQQ+439lf/wE+Z8YRBJ1NCmDr941C
            a58Ygzl/jF+/Qi7MztI7w4EdaiVqtumeR21vU6sEWDieTysCTWBIbM5vYsBwPbDU
            aAEJAhDsBcPFzFUr9DHt0gGTdkhZ1qBjoCMjrQ6DpnfsyrguCSt17VOZXqh/B1M5
            9FtfQxzE/Q6c0RqwGQir+8ZasgzJJm8p2i7ZlIzsHNJKFB/FJG5cjhdRfE7XCyFQ
            nubKMAMyJ8EA
            =opgc
            -----END PGP MESSAGE-----
          fp: 1F1AC5BB8445063D29B6F87C48A8C59F65012CDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
