apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: pilot
    labels:
        app: pilot
stringData:
    PILOT_DATABASE_URL: ENC[AES256_GCM,data:b4AEHErqHdgLFc6gSCJQJKfTfik5IKFpFSRfeBUa9xhy0DnYBQ1v2QZGdx/EBMuygzKcDYDe6G6MGT8scCo852w/a4tKxaRlz+6rjax59DD/dWvVpixN4b/qMAT8KYGjKT6Hip36XRIledkAthdLWrl6fxGbjRKQM3gL,iv:kI7kLl4nYmGodhSB72pnsP21KtOu9+E9cPAe71BygCE=,tag:uB/HYG0fTlE5dF3uOmL8Jg==,type:str]
    PILOT_FIREBASE_PROJECT_ID: ENC[AES256_GCM,data:ssExlisfrJTG++g=,iv:HgFkxdK9m3tPOYkngwEeqr+r3xjDJpP+SSgP/lSovmI=,tag:MUWs01osfj+h21+1uPWOMQ==,type:str]
    PILOT_HUBSPOT_KEY: ENC[AES256_GCM,data:yFj9kTfDWUYfOYsOmAkNMrXO4oVnCKmEMqopQaxriCJ2Q7gP,iv:z5j8aykkoynGQjGsgBSuaBt6xrIJI4s0jv1kRW3xDS0=,tag:8aLgP26k9e27Qj/ddoeVng==,type:str]
    PILOT_IMAGEKIT_KEY: ENC[AES256_GCM,data:ZjGC/vpnYIHCwoLL8XQLzkCdPtm7dRPVAQSFA/axs5aZ0/Ja,iv:AwnROzrcVGTMGnoAPuJoC4CasQRafG8956vH1j1JPdA=,tag:fQukFjyiwOnuYY7C/TcA7w==,type:str]
    PILOT_MAILGUN_DOMAIN: ENC[AES256_GCM,data:DKsHAj77f6yuRMG7Mh6Z,iv:HZdUXgaXLKKtK+6UCwNIPztp+f5aLLIZjp8Ogk/iZWM=,tag:3A70Xfzxcx5ELVQ7n3xP3g==,type:str]
    PILOT_MAILGUN_KEY: ENC[AES256_GCM,data:3R9dPPiqgHhXh/+0lTvdJiWfKPQ13uMZ30pK3Xxh/7pB4Lks,iv:NZ3mom6TQwxl7UYKQ99LeI1/O7xemfkRQ/BOFGAgL8I=,tag:WNwsVDrQnxvp67Y0C5s7Hw==,type:str]
    PILOT_SECRET_BASE: ENC[AES256_GCM,data:0r2Ew04NBQ5da4rf+WIyANGHLRCIkMcGxVR2zie5/kqU/VY/ywi0F32TZNMGnK5Z+D9B31q0Cwt/34vPkrG8ngFYdb29CrMHCU994pKTXA2J2bk6R3r/ZXEUDhPR6x9hVsvtQPvj0V3dzz3zWyxPLaCJr026JmOUs1iejtNinzU=,iv:8UD5yIu5bGjUuj/Gbx6pgm0dCIjjaN/hTo+g4tKYb+Q=,tag:nfpsKEdxfKlJGSEvDijRYQ==,type:str]
    PILOT_SENTRY_DSN: ENC[AES256_GCM,data:CiLRhIAcKNRGXgej8TN1sEXuCij10jfSs4zWYH5emh1J69+aW6lxlZWdBwdEuNgscrHtmBU5Px65uLjq8YQmLu0WvpCmm9fC6w==,iv:yY9g4mHQtPEvu+EWcQ2hS/1n8P9EZCaNTg8V5+weYIA=,tag:wVORz+Xmpkew0vjQCVqQNA==,type:str]
    PILOT_STRIPE_KEY: ENC[AES256_GCM,data:CI10paj6Gxf/z7bmUOG3GolZNPI6wQ8VFhxYUjubQbWi5fb18eqefstFiL3//lQuEhlXx2QqufZa0/XPruYunwNlJC8ESHH4tFdz0TP8erxiv86KhTNS8owglqzB7/o14uk+YpANrnULLEU=,iv:puGGPC8gdsgGr3r0GY97xU1rEvM17ltv0OgBt9+7+DQ=,tag:edtrWuAiXRqh+gF886swoA==,type:str]
    PILOT_STRIPE_SIGNING_SECRET: ENC[AES256_GCM,data:wmLACVl7euXOsZ2IugqZDCUbuuixyT2cSnaJg/P8xuTJHehSouQ=,iv:DIoirA2B10PukMXyL2XSvKL25EFjRPL1fylGdpF3ebQ=,tag:PLoFvy87MoeW5dEQJ3axMw==,type:str]
    PILOT_URLMETA_ID: ENC[AES256_GCM,data:8mH3UYdcBi/cu3ecGXdxnWudAf798Q==,iv:wl2AztgEiflrOi1EcET8V7F1cv4UCzDMUGuKGbxEg9s=,tag:Lw2VOCr5hdpm5N8BCryCPA==,type:str]
    PILOT_URLMETA_KEY: ENC[AES256_GCM,data:kKgUhx2Kpl2gQt+sMC34cMDt5hQ=,iv:3wC4xgAHzjAY88aPOZhBQ8eC0KRbBYL1vbQ2s2yKcZY=,tag:n4KJocw8a4SkTxCQkTUCmA==,type:str]
    OYSTER_ADMIN_KEY: ENC[AES256_GCM,data:FcuzCUGlfj8=,iv:Aki1oWdQEYF9voW2AmBjqFXQ+lfGtO+CuzCGDFTzrAc=,tag:DXzCvvuf/LKAW5vj5BZNUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-06T20:46:16Z"
    mac: ENC[AES256_GCM,data:+Bc+8nswf7tnA2JoqzP4jLw6NGXe79Z2bM6aP5ryP/+IwoX2RHkE+Q6iUBi5srYgUDXsHh/0S4oCwnXs03Yn12AkO0wDYjD4c9m8SL2KWKMRIs2Qcez/cjs8n09WWZSBWcvIwNRkSZYcYn7/hJxsA17OvpEwvrKB+FHmNZWL8Vw=,iv:cR5kR40SQz8KY+dkQG/EZNMZKekh5Kg0BhN1nVLjaCc=,tag:a8BT9BsyrorlEZco4iztLw==,type:str]
    pgp:
        - created_at: "2021-12-06T20:46:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1T4MNvPMvS9AQ//RX+VnbkHf0GRDlIVbnUXhw0uIl3MwYjZxL//ImS+4j0N
            /kl8Yzd2HNgBY158wTIdgl517mc0jdUYz3ZD/lEnKVVKrmkPGbdjq9Z4d1oEZnZZ
            7BarPxgYWZvCCrVpVMdoPqtFtpWvQL/bP2uOW0WvILjchSERLvK8Xa9Xr65wbM37
            VjjuqmJJPJHjga4hjeOCm/FLP+AwdUFfeH3KeQHQFqd417Nz0MBZ+lzIT4wE/Q3L
            sMdaUnc3Jc85u7lsC58xRza3F42TpHrsjsdgouhHFJ3adv9TQVEDhzyZEjLu/SQO
            hdGrjnjikDlV9rZ/qBCzFeem3wx8OFto3duNHtNB+iXnup7nLJMRCv+M3X5RZkHX
            oaIHv0UBlxHYiPTbRsttG1ldtmwCnHYweh5A+tOh+hgyLOSKgZceTetgxySNJCu9
            MXufQwTdHe/DmKhedB9gUYy7JnTa+c8FTNGf6TwT6PthA1bGkZI43VvEIETgvm0R
            nsdjv9df+JkykxexJphlxGzZ43O8rLIJMvsX8hwjVt4mHT4FQNFiNSKOECpsBzq0
            01oGo76F7AgSNdbSL0j8ApZF/QhS6g8KgwHz8qpL09n6L8g+Z4tw13/DLczJvwEd
            GU9g77r0Jv9/YRuf3Qkd4BpBLVtdLHjgCQw6/yWHjfGkHRToIx+fXGHjaCHC0MDU
            aAEJAhD2NvsSWSa/ArCsI9djUYhOXs+aSrFBapA2H9Fcg2fT/0Q7kzYfukwvEC7j
            9bbEI2wHlbqjtiZtZ/R9qBOvYeugBPE8ilobcIDZZT2QXyMC3gP3G9bv+47dafbA
            rnG5+ZA+ouLI
            =58JX
            -----END PGP MESSAGE-----
          fp: 1F1AC5BB8445063D29B6F87C48A8C59F65012CDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
