apiVersion: v1
kind: Secret
metadata:
    name: home
stringData:
    MONGO_DATABASE: ENC[AES256_GCM,data:jVq2RA==,iv:MmBKXAU8tbpdfXtLUgQZ/0z4D3vlT8BVZiQrN3lVm1s=,tag:x2viJSgpFegojLv6gOVsqA==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:kpJtXBHQa7sO7t68CVY48RWradf/FMNE4jnt6q7MX3yGyfR4WxkI+5DqaLRI19YIpQ8P2vW4bNCM6YkiLA7GEfGRyq9bFv1lPXP6VlbJeBn4c/Qn5CNEycw/k8Bnwfj881HKudHncg==,iv:SHHAAcqiLTo64dcXlm1lEIFcoHsd2wr3qWmsxU+5Ca0=,tag:qMmcYfYMtsmu4vV7BF/PDw==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:QsaKk4McarM0YKfICCfm1/QIlxZhvr2H6UWZCZdxMAU=,iv:ctrZgaLhzAXUNUzU+cF+uRoS7epmPu3PGL9lq91KjEM=,tag:12s1or3rbCUXYHoumDhbYg==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:8YYSGwldA+miNyYJkp10zC8RLyTYEq83s9wKzTUJzz0=,iv:8dJgFuMXhG6h5HE/o67+oefXLNjANMphJCPVj4ps3pw=,tag:pedxGo02oQLvSDRw/boIxg==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:wVqruKGfTVHX3N/96/MtWHZ9Bmm25b3i5KtkBhnOpACmcoq90Qwx7s9v5cRXRSv61bhbs77mm/DxOMLh7kOsIh+21pfy5DhbBnyrt4BBFO4ObOEEraq1BfUu/2sd3hUa7TdqIXptoDv8gWvSOCtdNtXN7AHLniqIHlVHqfdw0asvLIY=,iv:aO9ocUR/tqX0c0Jr68w9k84AiOzk6iDFR9rXBK073+Y=,tag:hXHwHGeyzU9WXQB2hVP+Tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-28T06:12:07Z"
    mac: ENC[AES256_GCM,data:1yDyrc9ABIli8it+TILjM4Fta3Qry0TI5OERwsM62Hh09xriRhWkq6cZ2rB85GL0O/AXS6B5zYRtke6fjpOuEdJE8r9M55xkDVsY5eYwj2QH0ltRZ28W8DpJVE8fmGxBUorT57PNdrOKCbcqaaWaavTJvuM3lgBFSkmSozOtiJc=,iv:oDM5phGj98lr2Ha1WamxtshZ8I7as1x8pCYwTSEjMYQ=,tag:FjTFE1rpnqvWjnw3vU836g==,type:str]
    pgp:
        - created_at: "2021-10-28T06:12:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1T4MNvPMvS9ARAAz0f1HPajhr/TRVMEAf75+6Z15ZgSuNtxU9hTWTpAAsnP
            WaRZMyoukbXWHjqJ56UsV2qbUGigdAfk8ScV/0JF62guVK6OGGaWvlR/YtNH1NiL
            hStCd6x0nTFr4ySR1RVhvpXlcQMRlR61/8YOcU5/S6iNsgVw4ZSYBAnKBqo8OLii
            TbE8vxvSaxFgJx0LCsfI+xX/ryniTQggO6QE0o4Sc1mBjPRb3v8BB3SlNj0tQvui
            WAMYMgbGAelLZC8NVlDDB145XybW7LdN9AE2Pp5MO3POHGqSxKanDRy3kvwGSMAu
            4XtP26dtYlWXDOaMYMaK4yZIYttranPirXsWT+RRy9oIaXXqVUHRGC5FPX/pDreO
            5mvQc6z+m+A+Pc71uQxgSLMDyxLsXMs+W5JloOEy/jutQpGDI8WTrfFcFk9k7NCA
            U/++CUGuY73BZlMgcjRUv4jxeR6ppXfJwB6xyx0QzA0YJQ+CaTrgMySsS7AWrZ0i
            OFECJWhWsLLs94wq7ANCM7WzXy8Fk62gtCtGzKMetj+FlNnRWawabzPZ+le2wtdZ
            taqA69onueEHzOPmCnG9hXvTrLLXy20VaS0qnBqxDFV989NtU42tP+PGp9lERpZV
            iMObyhMdIeHSZhwstlBgk1kjk0PFUihaJ5OR6ZAYxjh3ZRus9ZMsHljF4wqO2bbU
            ZgEJAhVYDl+OiNJPkZW5jkQcCZPiV37nK3dBuluq1pzMElOxdA4hQ7jw3tOAQVSt
            X8y78vo/eyh51Kjtj+J2iOeVyhCyaPHCfKH+EQPpKGptZxkjyrZ8rpUPYisgx3WN
            tyYVL8o3Tw==
            =+YCI
            -----END PGP MESSAGE-----
          fp: 1F1AC5BB8445063D29B6F87C48A8C59F65012CDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
