

apiVersion: v1
kind: Secret
metadata:
    name: home
data:
    MONGO_DATABASE: aG9tZQ==
    MONGO_URI: bW9uZ29kYitzcnY6Ly9qYXp6ZnVuazo5TENrdElzYVJBSkZEYnRPQGJlYW5idXJyaXRvLjBpcnoyLm1vbmdvZGIubmV0L2hvbWU/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
