apiVersion: v1
kind: Secret
metadata:
    name: icloud-config
stringData:
    config.yaml: ENC[AES256_GCM,data:02LVFhU2HrwgcGNPA6q/MdAyigmmH3mHpCPJfrUEz7Uemrs+q5K1RrZAGz0X3de57h51708kgdxhEpAT9wz7pQUaG1n+zbOlpNuijM1ImlUr9Of0+Yi2oUER6Vb+FJevdCNDtvbcisPrp7Tywc4VDlSdFr/0iuiyKLUzQ0nH7acd1Gc/PCGQ7MuKmLMClV/m04tzx/6hQl7IALqOBKuh72d6aa0B2b8W+JtJh2KzOXfpngsdCjcI1iMmbKNRZPDo2Qssw6hDOjePFizdiQ8=,iv:myyIxukOF6BucEtzbMngCUwZnLsr4WuJpaPQxu5wT9c=,tag:KpKliSGRI/STw2za0+IOuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-04T16:37:02Z"
    mac: ENC[AES256_GCM,data:GdsudS4AH39h4EPhH3Fl4TT5wDyo8InDKhpD3M/mryKDA+gnGpeXaRrs0wD5xgTSBYv52/lt7mBNaAq0/al3aJE++MVQnHk6Q2NjNuSyItDzYf0yfJjIYTvKFjuCpU8MYsvLhqBdI124/xyKgf+reL8STFbFa+AnT0n8zzC78p0=,iv:iuXnbcdZoPxFAB3rnN1EJy7iWvj+CZY5WsZqj9Au/6w=,tag:fTymfvZ5MFk18z/NSmu5Og==,type:str]
    pgp:
        - created_at: "2021-10-04T16:37:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1T4MNvPMvS9ARAAo3jP1FUIIMnqDJdEKad1OSljSumBSe+nXlsrEcAYYJct
            1BNDUgA+CiXPyB9C0A43FxOR/9t4uqMBHyjsgpydQ7JIMZxTivaYZw5cnq3UV21H
            G55G17z7erUiVkXh7U1UKlUJn01EbWbst0CM+BanDGSFPZlH4Z6WAHppAXzrW72z
            zNCZp4j+X8zfDpw73Yx3oKpZMFx0YZS1oDAclvMhfVrfLWf3a+G9iiuABAeTHMXK
            3bXplaoqGoLdCHhc6p6Y3aF4HZCtDQL49rm5fjUiiO1DqTiHKE/Fxg5+2k/ymAv7
            i+rk0O9whZsD0rjQLqHNm7b9uIuLfLjn8rv3FgOW2zHkmUKxCGltXknfy8jS0QtJ
            OyLkn49dG2kaQ541n+q2k/FUNmx5OamCDCCS3MQD29tKaB4nZAXnZ/bIyDZuJgeE
            kTjaZzaYS+y61djdzhb4CWKlLH2Wyaut+EzlqtVj23QSE1aWXLMsyiCAW9bbQswD
            fW2lhIGiI106nCw2a9UTNtkxvr0yFZdgqnOllw3UmESrjg1ZoJw1E8IHkbHmepu2
            OTyFcRqXTzhpdW3Tdnb5OdIeJdrhQPRzpN6ijQ3O4A1F/oy2sRF9zy5nVgOcZHXd
            axEhjM25kXnkWV2eFt1ncQHilOlvuyGTz3YLQSys7GM1/jQ/DMyf2tmlSRAPYxzU
            aAEJAhUYAfopcqMdnUWRdmZpDIOEVt7MzVv8eKKdAjjAIuqeeLvEM27YgEdyq2VJ
            fwYHu4adF/899QNsDL/CraiMy6OyC50kzpSAna1NSWZgXlgNisTRf/bAHqPy17Lf
            cVfyoARXtgOR
            =HJUJ
            -----END PGP MESSAGE-----
          fp: 1F1AC5BB8445063D29B6F87C48A8C59F65012CDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
