apiVersion: v1
kind: Secret
metadata:
    name: icloud-env
stringData:
    HTTPS_PROXY: ENC[AES256_GCM,data:D8QR0+mFHBGEeVq3GXoyDW2HfRARUofflI1sW6kZyWUR/ihjz7zYUtMHPt68DHAoHN46,iv:uxg0LCdyVeraZCpG5w6drPP9MQh1EVNNarXPtiKAgdU=,tag:umr536+8ChFRbO5x/wM+WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-04T16:36:48Z"
    mac: ENC[AES256_GCM,data:hJEIpEJmCLryoTzPE2OYCigHS2TLMM9CKGRwiqqjM5YpM0iBlmxwgAdFg0GmiNsbkU+uJga8k0FtoPrf1qf+aUC6CpRX5qg42RbJFP9RZzFwRSlOX2uMSMwaYTx8BzDHjVLTjnjagTUCmMRbyeePdU+dxuEBiguwAgFIjrzVvpE=,iv:DrXZDbiS6Ae634f7ejWnKcKIXYgT33kCRNM19a7C53o=,tag:uNOfuze0/wtynlKCb6+QVA==,type:str]
    pgp:
        - created_at: "2021-10-04T16:36:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1T4MNvPMvS9AQ//c/pWI1BLx3eHMj7MFhpINrX9gI5FUCm0d/S0iFhW6H77
            ZEFa0sA1Qmu8wMwVwRvkZCYjygHafVoEgSGlFRWSuNABp7/UetrSxMckGAQl6Uvj
            VkPu2HrM86ViOVnHhXYssK1v37pjniKqdh6tXG5Fzwpj9M30rRnxDT6aMHinu60I
            1jAqNXH9Igee7FJcjPUKjxszTTjsK3ijvBh/g6HgwwLC+Mf/bUj6mLYVrTolS/D9
            XAd5uyxRsmgghs+N1PZP9y6rOgHXHjjVS57HagQ9QcqWemRQ8WKMHdtYwRAB7km2
            QUHjoXX2QJrrBAiQS6MBTG1UH0Ry7ub4gS47czqU1uiEjZZ0qpbLyxUzSqaTgwtK
            1K2fMJoObWboE23E1npg6aVQ5vRWwbZ5oXEy1E7zPa6APhJki07/3xitR9g8oFJL
            jkuaXmEC98f8Dy86PMpo3KwThzC9rt2FEzD6AZwALjFPpf67HtpDmq0ttqk1ACSD
            SAkavc76u+CMJ1d3HQrgmVq0C/0F9zjba5tWn3ivWii3iDT/zmdnt/ad42VKFRdS
            lHwy+xJbPOLZJiBIhkqJj4TdLnsPXH8lCWNBJWUeTAqOaSi7onaVI2YNQa8DSQEK
            IXBfqSiZI7xdPjuO+mUWMrwlnpdQuEmgP6skyODFWPkSJaAd+IHDPo9odbCihcvU
            ZgEJAhUbr1gVUDbKbNrzNX7fwx7CSVqaClIqPkzWz23Hi3WcZiyfTEr259feiYMD
            EDsxhcAE9ILf3Z9eC8AKzVU6jStEbID3fN2zmGv9ZM3EIWXUD+85Xg/iF7OX8zcn
            ZhAg0J2Z+g==
            =mMSy
            -----END PGP MESSAGE-----
          fp: 1F1AC5BB8445063D29B6F87C48A8C59F65012CDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
