apiVersion: apps/v1
kind: Deployment
metadata:
  name: justchat-web
  labels:
    app: justchat
    component: web
spec:
  selector:
    matchLabels:
      app: justchat
      component: web
  template:
    metadata:
      labels:
        app: justchat
        component: web
    spec:
      containers:
        - name: server
          image: hulloitskai/justchat-web:0.1.1 # {"$imagepolicy": "flux-system:kai-justchat-web"}
          imagePullPolicy: IfNotPresent
          env:
            - name: JUSTCHAT_WEB_HOST
              value: "0.0.0.0"
            - name: JUSTCHAT_WEB_PORT
              value: "8000"
          envFrom:
            - configMapRef:
                name: justchat
            - secretRef:
                name: justchat
          ports:
            - name: http
              containerPort: 8000
          readinessProbe: &probe
            httpGet:
              path: /
              port: http
          livenessProbe: *probe
