---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kai
resources:
  - namespace.yaml
  - itskai-me.cert.yaml
  - icloud.volume.yaml
  - icloud.svc.yaml
  - icloud-env.secret.yaml
  - icloud-config.secret.yaml
  - icloud.deploy.yaml
  - home.configmap.yaml
  - home.secret.yaml
  - home-api.deploy.yaml
  - home-api.ingressroute.yaml
  - home-api.svc.yaml
  - home-web.deploy.yaml
  - home-web.ingressroute.yaml
  - home-web.svc.yaml
  - justchat.configmap.yaml
  - justchat.secret.yaml
  - justchat-api.deploy.yaml
  - justchat-api.ingressroute.yaml
  - justchat-api.svc.yaml
  - justchat-web.deploy.yaml
  - justchat-web.ingressroute.yaml
  - justchat-web.svc.yaml
