apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: docker-tugolo
data:
    .dockerconfigjson: ENC[AES256_GCM,data:EiZJ6GfEmzjYNIdojAASGnLASWqUreBjx5bR5OcYvbm06/qhMupnUSKUb4Y2IQqGCCBConV0VnDFSR77+LwDVIHYOp5RRLN8ZC8dVatWiu5Plqf2HXJnIgGrt4tRpkxLYvy1/5TRZHO3Fj6pSlGhNV7vdc7nZyNW5b3AlRj3wbNeYihmHOBT+ZRkhs3b7HlKbT7lzbeCPGMLC6YOT2pV4rz2wSf8nKp/ixgMcUU4GMrJTveYlqOEidEEDCVOh0quSiElo5PozJOWQJ2gASkXqDKv7Ra5JRXmAk7moAkCr0Le9CeGmbKhu1qE0ZU4tLSdcHSDZBo59AjfwnJ6K55Wqw==,iv:EZ9lBOvYzl9rLxqAEjMrZSLgF6KcK6OgC2rmkLfHQC8=,tag:xg93IqghilrAW44bHAs+TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-06T10:59:42Z"
    mac: ENC[AES256_GCM,data:x0TAXtOwdKC6L5acCcZd/sNKYpBeg0z6/Z1HEHZdqUZwmAb9ck/xDykrS2eUOTiv4LmdjBU4NVrIriXiCJ3bJsVApSeE53inUAg7DAHiwJltSdmpSlzEWBef1qiZjLsVt9wjeyjkGRfosJFlu7C3tI9bqhImpbuzbscMsi2srjM=,iv:JY1s/O6OniDZ3qHjqI1ovpEfdDbSevGKILore720LXk=,tag:v4QrvHPlsZNP8PAjTdG0tg==,type:str]
    pgp:
        - created_at: "2021-12-06T10:59:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1T4MNvPMvS9ARAAnKIOYdcDvmSFzdcqCdrkBZu4Q26rQMTZKiab4SzaeEi/
            fj5cmAcy8KUwOWVyrs0f5G9DQ8BMQTUXpvHel5DwMAgiHuvbfEnYL1IFErKuHcI2
            Z7FcA0LEwscbfSWUIRCa/LAlQ+nbgOGm67nmKZlJJbjLUIjwwE/2tJHGxkY5uvR8
            sKkfUYZ+xp57MBuSvhX0QC/zucQ988+Xi9bqrWRNvtyLBH4SXPcoXbeVB6HDumtP
            SoVeI12YzAqOKUjcNdscbnsKnILYyC8kRFGgqKY/ntgVs2TFgLyySG+LDNfDhV/H
            NPGtaQDRjcEHlUlIBrNTXglHzzZJqk3eEoEMrKGdD8t+vWPsmyjNOOZhTbkYnj/H
            I64RQXVvnd4AiT2d3bXCcIUdcRzCFU/hDg7PARxF4YcuHPlSWLiKvT0ouHDxmTAD
            543vSN2UQwwrFbP1MDaMbpyr5PtJ2hVLAFZZN9hD2UfI4UDZM6czRqTFROI3bxde
            9sH+RW5psbk25IRzxVyLg8XxdO9Axi2hKgmpqmX5rVGsk8l4NzOtsoQKKqVCiIHT
            6cAoua5jRXR70XGjAKO/8l0Z4KkudGsYaG+tHWW9bvbKZP2WPMsQOqtw53TD2M8G
            Mt9USQFj6ZybuWUEBR3pbSIC6D6xdswd9+g4XVUfKDedyjIrTyXoWDx22vtxx7fU
            aAEJAhCo973p2mNl0C+ORfnYUyTSTkzPJZsGXU7TQA9fFdwLIIM9FxYQoCxKN0dD
            E1wdeRXvhHMJF+fzQF4WOpOgt6lpR1T8k/yNvCdEg1mb6DTAoeL8RODfWQ9FICzG
            kXDUMEAUP7bM
            =sX9L
            -----END PGP MESSAGE-----
          fp: 1F1AC5BB8445063D29B6F87C48A8C59F65012CDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
