apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: oyster
stringData:
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:yF+aB+TDuRS2ZMKYPfJw+06X9Hg2aRSVd4XLDBbEK+o=,iv:aMcSL+PKro0UHywHD/rQugPYNpc4LxK5QAFKkKvSgEc=,tag:svfgPuhVwVVJYuvtOCgvGw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:F6gjSymn0zsEh8DLQT1/lz2XowLkUM4/5CZEC+n+XcWwd8/NUhJigA==,iv:Bm05wtWat4uYL3wxQblDIEzH4lmoWwlRP7/3UTY/16c=,tag:HwdeGh+WeNT2192kwP9XQw==,type:str]
    CHATENGINE_PRIVATE_KEY: ENC[AES256_GCM,data:4hzJPF7v1dn2rzZflxkhDnNOf3BL1IdoaYvXXZYcutGRXY1s,iv:yEZdGwpJTJAFs+BIFUu5SFPeWwFDLmZd3i0S/hHVsNs=,tag:3TYdlec57UwaTNlXfL88kQ==,type:str]
    CHATENGINE_SECRET: ENC[AES256_GCM,data:802o/muPdaaehmPhgoN2wOhUPtfUM39aMFkvoGHAUMc=,iv:z612no8MGktmls57iV+OyqiQ5GBpxlk+ffLkJNnHMrA=,tag:U7ZemwcB6urhLcUhYG6tPQ==,type:str]
    COURIER_API_KEY: ENC[AES256_GCM,data:/CRzaO8e59FU6Z9C2LRAv7T4cQIWcxdFjnxLP6Bt43h7tb0L,iv:kmLHcWytqbF+rb1poVx9Hc5msazxH4fEtfWTRaLtuF0=,tag:fRHRyo1qn8cz/lTXsu8FJQ==,type:str]
    GCP_API_KEY: ENC[AES256_GCM,data:bcYzqHyTlzwYHWXtaRzZMjyvHdNWttYNfADbXc5LxiMH9HVtoHXw,iv:2nYqhnXk2o5wzuv++Xhk5uhILL+8zfrHgNuWlGYxWUU=,tag:w2nSY9gJ0Etk/FoEETy7kw==,type:str]
    HUBSPOT_API_KEY: ENC[AES256_GCM,data:1DoJoZqdLdAVcRbcvO921x/eu/7YSSPMaOls2A5eQb4+ckIs,iv:Uff5IR7b+dz9dAmFB2bwuaOz0MfafaVX5wfmMN8HFso=,tag:l+sU2UcgMbTmzU2pcIDyiA==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:wCUXSvLI1TrnwWUzXiOIfKkX3LeSzJzHXAaolCoJUBKRlaB5YffKDndCNzSSkf2GiIU7cloQCD6aAVH93J+jqNegsvvYejtHKzRkpLUL4XFxoRyZ2obAXruuto50CUxYyS3UMw==,iv:biFItB1xG0ATBPtqbK6bDixREKQ8CWoYnnJipMq0XZg=,tag:oLjf9OU6T9zQaCPBt8eUmQ==,type:str]
    OYSTER_ADMIN_SECRET: ENC[AES256_GCM,data:OrCpNHtcbwI=,iv:tSNJ5MjfL9weF7qUujW5sj9eKpNknVX/PPN06exWTIQ=,tag:pcCgPfYVXdkkcf4SFNlgjw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:3V5ydx9Oxg/vnsK79Bv83HNO13hdsPKUJwgS4iaxCzGEfQb2+S6Rx+53D24shGEEnz0=,iv:pN36Qx/F4XQqcSXPF8s8JvJHA9mknYeCqy9cwb3J4UI=,tag:aEjk19cHf3z3c0SvCymyeA==,type:str]
    URLMETA_API_EMAIL: ENC[AES256_GCM,data:ICnASXLQUlGGtPUd6a0wDWZqOHg5MA==,iv:l1YTDVwwnmJ3C04sl5Mbj3qob0CWzTfvGQR43DyWreQ=,tag:w29YZGX4QAHs0JlhkRZB0g==,type:str]
    URLMETA_API_KEY: ENC[AES256_GCM,data:cgalGNoXUuoyoJd2R09XB8qUxsU=,iv:UNyxP4JN+PZVq9mNxYGNvMiGk9YpJ/mbFIInxMADxuI=,tag:8zFhLF8du7wiA0HqvxlwMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-06T12:47:23Z"
    mac: ENC[AES256_GCM,data:5xDLlJMem0iZWaIK57nfPPBtYsXwC0VDIClsJrumiEPot3kSbBpV8gAeSl9orDlQfaN+rYKJTd+ZacKeISjQtmiTMJKrNiIx/bk6ptwcpN+af3r1PwTGaW9xAOBHVZu7EDSEx4vNNrehKF2tpWfF/hSrOGGFiq4dWbBLd4tQW4A=,iv:/Cxo4hI4F9g2bBbKoN8abbkJfTB9j6eRirIySNqaSU0=,tag:Sx1L4b7J6MhQsA/btx2aWg==,type:str]
    pgp:
        - created_at: "2021-12-06T12:47:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1T4MNvPMvS9ARAAmvaYSfFnYvOMAa2cftQWbQun4sbCADXQRZp06Wz6+Lb0
            hUMSzCK+Hg6wBBfJ39P45kE7iWYHSuR6wqy3JDYXaEB9Jer/7/o2qVT7031ljlbB
            fvZ9OnVm2q8HKb3mOuMc4XWMCgPodLrS5nbjfE0YbCXYAugNsFg77H85pqkL/qKP
            2LtxZjpX9joorJh9OX3epgY2mmvmQSRjD07m0Zz+GTRi1fkMFyfHTZTdBaRTHWdk
            93WTcMYNl4gZnfcMZMq6uJLIvFG5iRVnrsjZ8FzFBAf9Ww0ci9vWIfCTF/q56IS/
            Tx1WG8cR1H+imk5rsjoHgqFUvEfF7x9nz1RCLgMmtoI2N459GnRdYtuN7jrSt2j4
            90v5UF96gU8Vnlnla7/cRb+s47t6QI1rJDoQAx4/Z9YGc8srLF6Fa9Ctd9UIdzdZ
            A5/AxVv7C+uLpwr613IV30KtismDAOOQB7GE4xXtr2R3W2bN2MbJmz0isT+Kys/G
            ctpYQCwO0DEBicu7a+NExvVy0KdP/tTRXAaUJQiVrvWF+vCxsY48H9vbvSsmY0tp
            mJCsuHnedNiHUVs2lLo/xWCKOVbrWAEPsKeOM+6Z0BZbGVNE73izW2600O5MyPgq
            GNzaPj5OkXgniK+RoembhoEhWtHOpjn5/anKYIIiqmIs2SWqkcfDtQzP0yLFF0nU
            aAEJAhAGuRIW3aSh1wV1BsR0zGoDbnAYnLxrrnEjzL2PciMeSLbEKJXZNWYsQPbH
            aVHoeuHRG1EfOS3IRNu56sHjXLD1bz1mcEMyHJ8n7WeaogFhsE8UHS+FtBndE4W6
            NzJ+dkmJ26vb
            =MC3i
            -----END PGP MESSAGE-----
          fp: 1F1AC5BB8445063D29B6F87C48A8C59F65012CDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
