---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
resources:
  - namespace.yaml
  - cert-manager.helmrelease.yaml
  - cloudflare.secret.yaml
  - letsencrypt-prod.clusterissuer.yaml
  - letsencrypt-staging.clusterissuer.yaml
