---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization

metadata:
  name: systems
  namespace: flux-system

spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: cluster/systems
  prune: false
  validation: client
  interval: 10m0s
