---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: traefik

spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 10.3.2
  interval: 1h0m0s
  values:
    image:
      repository: traefik # {"$imagepolicy": "flux-system:default-traefik:name"}
      tag: 2.5.2 # {"$imagepolicy": "flux-system:default-traefik:tag"}
    additionalArguments:
    - --entrypoints.web.http.redirections.entryPoint.to=:443
    - --entrypoints.web.http.redirections.entryPoint.permanent=false
    logs:
      general:
        level: INFO
    ports:
      traefik:
        expose: true
      web:
        hostPort: 80
      websecure:
        hostPort: 443
        tls:
          enabled: true
    metrics: {}
    service:
      type: ClusterIP
    nodeSelector:
      role: ingress
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 300m
        memory: 150Mi
