---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

metadata:
  name: apps

spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
  path: ./apps
  prune: true
  validation: client
  interval: 1m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
