---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization

metadata:
  name: charts
  namespace: flux-system

spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: cluster/charts
  prune: true
  validation: client
  interval: 10m0s
