---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
resources:
  - itskai-me.certificate.yaml
  - traefik-dashboard.ingressroute.yaml
  - metrics.helmrelease.yaml
