---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy

metadata:
  name: bedda-travel-oyster-api

spec:
  imageRepositoryRef:
    name: bedda-travel-oyster-api
  policy:
    semver:
      range: 0.x-x
