---

apiVersion: v1
kind: ConfigMap

metadata:
  name: home-api

data:
  ENV: production
  LOG: info,api=debug
  BASE_URL: https://itskai.me/api
  WEB_BASE_URL: https://itskai.me
  AUTH0_ISSUER_BASE_URL: https://itskai.us.auth0.com
  OBSIDIAN_VAULT_PATH: /icloud/Obsidian/Kai
